condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
match_block_trailing_comma = true
normalize_doc_attributes = true
style_edition = "2024"
unstable_features = true
wrap_comments = true
